# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x0b\x65ventdriven\"Q\n\x05\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\x1f\n\rEventResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8e\x01\n\x0c\x45ventService\x12;\n\tSendEvent\x12\x12.eventdriven.Event\x1a\x1a.eventdriven.EventResponse\x12\x41\n\rReceiveEvents\x12\x12.eventdriven.Event\x1a\x1a.eventdriven.EventResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=28
  _globals['_EVENT']._serialized_end=109
  _globals['_EVENTRESPONSE']._serialized_start=111
  _globals['_EVENTRESPONSE']._serialized_end=142
  _globals['_EVENTSERVICE']._serialized_start=145
  _globals['_EVENTSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
